<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ajaxselectlist"
 *
 * Auto generated by Extension Builder 2016-07-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Select list with Ajax call',
	'description' => 'Provides a drop-down list which uses  Ajax to load records into the page.',
	'category' => 'plugin',
	'author' => 'Sebastian Klein',
	'author_email' => 'sebastian@sklein-medien.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);